// Copyright 2026 coral-rust contributors
// Licensed under the BSD-2-Clause license.
//
// End-to-end tests for coral-pig.

use coral_pig::to_pig_latin;

fn normalize(s: &str) -> String {
    s.lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty() && !l.starts_with("--"))
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn plain_select_load_and_foreach() {
    let p = to_pig_latin("SELECT id, name FROM employees").unwrap();
    let n = normalize(&p);
    assert!(n.contains("LOAD 'employees'"), "{n}");
    assert!(n.contains("FOREACH t0 GENERATE id, name"), "{n}");
    assert!(n.contains("OUT = t1"), "{n}");
}

#[test]
fn where_becomes_filter() {
    let p = to_pig_latin("SELECT id FROM t WHERE salary > 0").unwrap();
    let n = normalize(&p);
    assert!(n.contains("FILTER t0 BY (salary > 0)"), "{n}");
}

#[test]
fn group_by_with_count_and_avg() {
    let p = to_pig_latin(
        "SELECT dept, COUNT(*) AS n, AVG(salary) AS avg_sal
         FROM employees
         GROUP BY dept",
    )
    .unwrap();
    let n = normalize(&p);
    assert!(n.contains("GROUP t0 BY (dept)"), "{n}");
    assert!(n.contains("COUNT(t0)"), "{n}");
    assert!(n.contains("AVG(t0.salary) AS avg_sal"), "{n}");
    assert!(n.contains("FLATTEN(group)"), "{n}");
}

#[test]
fn having_becomes_trailing_filter() {
    let p = to_pig_latin(
        "SELECT dept, COUNT(*) AS n
         FROM employees
         GROUP BY dept
         HAVING COUNT(*) > 3",
    )
    .unwrap();
    let n = normalize(&p);
    // HAVING is rendered on the FOREACH output, not on the raw group bag.
    // The critical property is that there's a second FILTER step after
    // the group-by FOREACH.
    let filter_count = n.matches("FILTER").count();
    assert!(filter_count >= 1, "{n}");
    assert!(n.contains("HAVING") || n.contains("COUNT(*) > 3"), "{n}");
}

#[test]
fn inner_join_uses_pig_join_by() {
    let p = to_pig_latin(
        "SELECT a.id, b.name
         FROM a
         JOIN b ON a.k = b.k",
    )
    .unwrap();
    let n = normalize(&p);
    assert!(n.contains("LOAD 'a'"), "{n}");
    assert!(n.contains("LOAD 'b'"), "{n}");
    assert!(n.contains("JOIN t0 BY k, t1 BY k"), "{n}");
}

#[test]
fn left_outer_join() {
    let p = to_pig_latin(
        "SELECT a.id, b.name
         FROM a LEFT JOIN b ON a.k = b.k",
    )
    .unwrap();
    assert!(p.contains("JOIN LEFT OUTER"), "{p}");
}

#[test]
fn order_by_emits_order_step() {
    let p = to_pig_latin("SELECT id FROM t ORDER BY id DESC").unwrap();
    let n = normalize(&p);
    assert!(n.contains("ORDER"), "{n}");
    assert!(n.contains("id DESC"), "{n}");
}

#[test]
fn limit_emits_limit_step() {
    let p = to_pig_latin("SELECT id FROM t LIMIT 10").unwrap();
    let n = normalize(&p);
    assert!(n.contains("LIMIT"), "{n}");
    assert!(n.ends_with("OUT = t2;"), "{n}");
}

#[test]
fn qualified_table_name_uses_full_path() {
    let p = to_pig_latin("SELECT id FROM hr.employees").unwrap();
    assert!(p.contains("LOAD 'hr.employees'"), "{p}");
}

#[test]
fn script_starts_with_auto_generated_header() {
    let p = to_pig_latin("SELECT 1 FROM t").unwrap();
    assert!(p.starts_with("-- Auto-generated by coral-pig"), "{p}");
}

#[test]
fn aliased_expression_projection() {
    let p = to_pig_latin("SELECT id * 2 AS doubled FROM t").unwrap();
    let n = normalize(&p);
    assert!(n.contains("id * 2 AS doubled"), "{n}");
}

#[test]
fn full_pipeline_ends_at_out() {
    let p = to_pig_latin(
        "SELECT dept, COUNT(*) AS n
         FROM employees
         WHERE salary > 0
         GROUP BY dept
         HAVING COUNT(*) > 1
         ORDER BY n DESC
         LIMIT 5",
    )
    .unwrap();
    let n = normalize(&p);
    let last_line = n.lines().last().unwrap();
    assert!(last_line.starts_with("OUT ="), "last line: {last_line}");
    assert!(n.contains("FILTER"), "{n}");
    assert!(n.contains("GROUP"), "{n}");
    assert!(n.contains("ORDER"), "{n}");
    assert!(n.contains("LIMIT"), "{n}");
}
