// Copyright 2026 coral-rust contributors
// Licensed under the BSD-2-Clause license.

//! Pig Latin output backend for coral-rust.
//!
//! Rust port of Java `coral-pig`'s `RelToPigLatinConverter` for the
//! common SELECT / FROM / WHERE / GROUP BY / JOIN / aggregate shape.
//! Deliberately NOT a full RelNode-driven translator — we operate
//! directly on the sqlparser AST, which keeps the crate dependency
//! graph tiny (just sqlparser + thiserror) and the code
//! inspect-in-five-minutes.
//!
//! # What Pig Latin you get
//!
//! For a query like:
//!
//! ```sql
//! SELECT dept, COUNT(*) AS n, AVG(salary) AS avg_sal
//! FROM employees
//! WHERE salary > 0
//! GROUP BY dept
//! ```
//!
//! this crate produces:
//!
//! ```pig
//! -- Auto-generated by coral-pig
//! t0 = LOAD 'employees' USING PigStorage();
//! t1 = FILTER t0 BY (salary > 0);
//! t2 = GROUP t1 BY (dept);
//! OUT = FOREACH t2 GENERATE FLATTEN(group) AS (dept), COUNT(t1) AS n, AVG(t1.salary) AS avg_sal;
//! ```
//!
//! The final alias is always `OUT`; intermediates are `t0`, `t1`, ….
//!
//! # Scope
//!
//! | Feature          | Supported        |
//! |------------------|------------------|
//! | SELECT columns   | ✅               |
//! | Expression projections (`a + b`, `NVL(x,0)`) | ✅ rendered via sqlparser's Display |
//! | WHERE            | ✅               |
//! | GROUP BY + aggregates (SUM/COUNT/AVG/MIN/MAX) | ✅ |
//! | JOIN (inner, left, right, full)   | ✅ basic `a.k = b.k` form |
//! | HAVING           | ✅ translated to trailing FILTER |
//! | ORDER BY         | ✅ → ORDER … BY … |
//! | LIMIT            | ✅ → LIMIT        |
//! | Nested subqueries / CTEs | ⚠️ not expanded — use inline CTE first |
//! | UDFs             | Emitted as `my_udf(args)` — you DEFINE it yourself |
//!
//! Anything unsupported round-trips through as a `-- unsupported` comment,
//! so you can diff against the generated script and patch manually.

pub mod error;
pub mod render;

pub use error::{PigError, Result};
pub use render::to_pig_latin;
