// Copyright 2026 coral-rust contributors
// Licensed under the BSD-2-Clause license.

//! SQL AST → Pig Latin rendering.

use sqlparser::ast::{
    BinaryOperator, Expr, GroupByExpr, Join, JoinConstraint, JoinOperator, ObjectName, OrderByExpr,
    Query, Select, SelectItem, SetExpr, Statement, TableFactor, TableWithJoins, Value,
};
use sqlparser::dialect::PostgreSqlDialect;
use sqlparser::parser::Parser;

use crate::error::{PigError, Result};

/// Translate a SQL statement (or multiple — first is used) to Pig Latin.
/// Returns the Pig script as a single `\n`-separated string. The final
/// alias is always `OUT`.
pub fn to_pig_latin(sql: &str) -> Result<String> {
    let stmts = Parser::parse_sql(&PostgreSqlDialect {}, sql)?;
    let stmt = stmts.first().ok_or(PigError::NoSelect)?;
    let query = match stmt {
        Statement::Query(q) => q,
        Statement::CreateView { query, .. } => query,
        _ => return Err(PigError::Unsupported("expected SELECT or CREATE VIEW".into())),
    };
    let select = unwrap_select(query)?;
    let mut ctx = PigCtx::default();
    render_query(query, &select, &mut ctx);
    Ok(ctx.finish())
}

#[derive(Default)]
struct PigCtx {
    lines: Vec<String>,
    counter: u32,
}

impl PigCtx {
    fn alloc(&mut self) -> String {
        let name = format!("t{}", self.counter);
        self.counter += 1;
        name
    }
    fn emit(&mut self, line: String) {
        self.lines.push(line);
    }
    fn finish(self) -> String {
        let mut out = String::from("-- Auto-generated by coral-pig\n");
        for l in self.lines {
            out.push_str(&l);
            out.push('\n');
        }
        out.trim_end().to_string() + "\n"
    }
}

fn unwrap_select(q: &Query) -> Result<Select> {
    match q.body.as_ref() {
        SetExpr::Select(s) => Ok(*s.clone()),
        other => Err(PigError::Unsupported(format!("query body: {other:?}"))),
    }
}

// -------------------------------------------------------------------
// Top-level rendering
// -------------------------------------------------------------------

fn render_query(q: &Query, sel: &Select, ctx: &mut PigCtx) {
    // 1. LOAD + JOINs → one alias representing the FROM clause.
    let from_alias = render_from(&sel.from, ctx);

    // 2. WHERE
    let mut current = from_alias;
    if let Some(predicate) = &sel.selection {
        let next = ctx.alloc();
        ctx.emit(format!("{next} = FILTER {current} BY ({});", render_expr(predicate)));
        current = next;
    }

    // 3. GROUP BY (+ aggregates, if any).
    let is_aggregate = matches!(&sel.group_by, GroupByExpr::Expressions(e, _) if !e.is_empty())
        || projection_has_aggregate(&sel.projection);

    if is_aggregate {
        // GROUP BY → GROUP foo BY (keys);
        let group_alias = ctx.alloc();
        let keys = match &sel.group_by {
            GroupByExpr::Expressions(es, _) if !es.is_empty() => {
                es.iter().map(render_expr).collect::<Vec<_>>().join(", ")
            }
            _ => "ALL".to_string(),
        };
        let input_alias = current.clone();
        ctx.emit(format!("{group_alias} = GROUP {input_alias} BY ({keys});"));
        current = group_alias;

        // Projection → FOREACH t2 GENERATE FLATTEN(group) AS (keys), AGG(...) AS name
        let parts = render_group_projection(&sel.projection, &input_alias, &sel.group_by);
        let proj_alias = ctx.alloc();
        ctx.emit(format!("{proj_alias} = FOREACH {current} GENERATE {parts};"));
        current = proj_alias;
    } else {
        // Plain SELECT cols
        let parts = render_simple_projection(&sel.projection, &current);
        let proj_alias = ctx.alloc();
        ctx.emit(format!("{proj_alias} = FOREACH {current} GENERATE {parts};"));
        current = proj_alias;
    }

    // 4. HAVING → trailing FILTER.
    if let Some(having) = &sel.having {
        let next = ctx.alloc();
        ctx.emit(format!("{next} = FILTER {current} BY ({});", render_expr(having)));
        current = next;
    }

    // 5. ORDER BY.
    if let Some(ord) = &q.order_by {
        if !ord.exprs.is_empty() {
            let next = ctx.alloc();
            let keys = render_order_keys(&ord.exprs);
            ctx.emit(format!("{next} = ORDER {current} BY {keys};"));
            current = next;
        }
    }

    // 6. LIMIT.
    if let Some(lim) = &q.limit {
        let next = ctx.alloc();
        ctx.emit(format!("{next} = LIMIT {current} {};", render_expr(lim)));
        current = next;
    }

    // Final rebase to the canonical OUT alias.
    ctx.emit(format!("OUT = {current};"));
}

// -------------------------------------------------------------------
// FROM / joins
// -------------------------------------------------------------------

fn render_from(from: &[TableWithJoins], ctx: &mut PigCtx) -> String {
    if from.is_empty() {
        let alias = ctx.alloc();
        ctx.emit(format!("{alias} = -- <empty FROM>"));
        return alias;
    }
    if from.len() > 1 {
        // Comma-separated FROM (implicit CROSS). Translate first,
        // then CROSS-join the rest.
        let mut acc = render_table_with_joins(&from[0], ctx);
        for other in &from[1..] {
            let rhs = render_table_with_joins(other, ctx);
            let next = ctx.alloc();
            ctx.emit(format!("{next} = CROSS {acc}, {rhs};"));
            acc = next;
        }
        return acc;
    }
    render_table_with_joins(&from[0], ctx)
}

fn render_table_with_joins(twj: &TableWithJoins, ctx: &mut PigCtx) -> String {
    let mut current = render_table_factor(&twj.relation, ctx);
    for join in &twj.joins {
        current = render_join(&current, join, ctx);
    }
    current
}

fn render_table_factor(f: &TableFactor, ctx: &mut PigCtx) -> String {
    match f {
        TableFactor::Table { name, .. } => {
            let alias = ctx.alloc();
            let path = path_for_table(name);
            ctx.emit(format!(
                "{alias} = LOAD '{path}' USING PigStorage();"
            ));
            alias
        }
        TableFactor::Derived { subquery, .. } => {
            let sel = match subquery.body.as_ref() {
                SetExpr::Select(s) => *s.clone(),
                _ => {
                    let alias = ctx.alloc();
                    ctx.emit(format!("{alias} = -- unsupported derived table"));
                    return alias;
                }
            };
            render_query(subquery, &sel, ctx);
            // Last "OUT" will be overwritten — re-alias right now.
            let alias = ctx.alloc();
            ctx.emit(format!("{alias} = OUT;"));
            alias
        }
        other => {
            let alias = ctx.alloc();
            ctx.emit(format!(
                "{alias} = -- unsupported table factor: {:?}",
                discriminant(other)
            ));
            alias
        }
    }
}

fn render_join(lhs: &str, join: &Join, ctx: &mut PigCtx) -> String {
    let rhs = render_table_factor(&join.relation, ctx);
    let (kind, on_expr): (&str, Option<&Expr>) = match &join.join_operator {
        JoinOperator::Inner(JoinConstraint::On(e)) => ("JOIN", Some(e)),
        JoinOperator::LeftOuter(JoinConstraint::On(e)) => ("JOIN LEFT OUTER", Some(e)),
        JoinOperator::RightOuter(JoinConstraint::On(e)) => ("JOIN RIGHT OUTER", Some(e)),
        JoinOperator::FullOuter(JoinConstraint::On(e)) => ("JOIN FULL OUTER", Some(e)),
        JoinOperator::CrossJoin => ("CROSS", None),
        other => {
            let alias = ctx.alloc();
            ctx.emit(format!(
                "{alias} = -- unsupported join: {:?}",
                discriminant(other)
            ));
            return alias;
        }
    };
    let next = ctx.alloc();
    match (kind, on_expr) {
        ("CROSS", _) => ctx.emit(format!("{next} = CROSS {lhs}, {rhs};")),
        (_, Some(e)) => {
            let (l_key, r_key) = split_join_keys(e).unwrap_or_else(|| {
                // Fallback: emit as-is.
                ("__l__".into(), "__r__".into())
            });
            ctx.emit(format!(
                "{next} = {kind} {lhs} BY {l_key}, {rhs} BY {r_key};"
            ));
        }
        _ => ctx.emit(format!(
            "{next} = -- unsupported join form between {lhs} and {rhs}"
        )),
    }
    next
}

fn split_join_keys(e: &Expr) -> Option<(String, String)> {
    // Expect `a.x = b.y` — extract the two sides.
    if let Expr::BinaryOp { left, op: BinaryOperator::Eq, right } = e {
        return Some((
            strip_qualifier(&render_expr(left)),
            strip_qualifier(&render_expr(right)),
        ));
    }
    None
}

fn strip_qualifier(s: &str) -> String {
    // "a.x" → "x"
    s.rsplit('.').next().unwrap_or(s).to_string()
}

fn path_for_table(name: &ObjectName) -> String {
    name.0
        .iter()
        .map(|i| i.value.clone())
        .collect::<Vec<_>>()
        .join(".")
}

// -------------------------------------------------------------------
// Projections
// -------------------------------------------------------------------

fn render_simple_projection(items: &[SelectItem], _from_alias: &str) -> String {
    items
        .iter()
        .map(|i| match i {
            SelectItem::UnnamedExpr(e) => render_expr(e),
            SelectItem::ExprWithAlias { expr, alias } => {
                format!("{} AS {}", render_expr(expr), alias.value)
            }
            SelectItem::Wildcard(_) => "*".to_string(),
            SelectItem::QualifiedWildcard(n, _) => format!("{n}.*"),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_group_projection(items: &[SelectItem], src: &str, group_by: &GroupByExpr) -> String {
    let key_names: Vec<String> = match group_by {
        GroupByExpr::Expressions(es, _) => {
            es.iter().map(|e| strip_qualifier(&render_expr(e))).collect()
        }
        _ => vec![],
    };
    let mut parts = Vec::with_capacity(items.len());
    for item in items {
        let (expr, alias) = match item {
            SelectItem::UnnamedExpr(e) => (e.clone(), None),
            SelectItem::ExprWithAlias { expr, alias } => {
                (expr.clone(), Some(alias.value.clone()))
            }
            SelectItem::Wildcard(_) => {
                parts.push("*".to_string());
                continue;
            }
            SelectItem::QualifiedWildcard(n, _) => {
                parts.push(format!("{n}.*"));
                continue;
            }
        };

        // Group-key reference → FLATTEN(group.<name>)
        // Aggregate: map to Pig built-in + use `src` bag.
        let rendered = if is_group_key(&expr, &key_names) {
            let name = strip_qualifier(&render_expr(&expr));
            if key_names.len() == 1 {
                format!("FLATTEN(group) AS {name}")
            } else {
                format!("FLATTEN(group).{name} AS {name}")
            }
        } else if let Some(agg) = aggregate_form(&expr, src) {
            agg
        } else {
            render_expr(&expr)
        };
        let final_text = match alias {
            Some(a) if !rendered.contains(" AS ") => format!("{rendered} AS {a}"),
            _ => rendered,
        };
        parts.push(final_text);
    }
    parts.join(", ")
}

fn is_group_key(expr: &Expr, keys: &[String]) -> bool {
    keys.iter()
        .any(|k| k == &strip_qualifier(&render_expr(expr)))
}

fn projection_has_aggregate(items: &[SelectItem]) -> bool {
    items.iter().any(|i| match i {
        SelectItem::UnnamedExpr(e) | SelectItem::ExprWithAlias { expr: e, .. } => {
            contains_aggregate(e)
        }
        _ => false,
    })
}

fn contains_aggregate(e: &Expr) -> bool {
    if let Expr::Function(f) = e {
        let name = f
            .name
            .0
            .last()
            .map(|i| i.value.to_ascii_uppercase())
            .unwrap_or_default();
        matches!(
            name.as_str(),
            "COUNT" | "SUM" | "AVG" | "MIN" | "MAX" | "COLLECT_LIST" | "COLLECT_SET"
        )
    } else {
        false
    }
}

fn aggregate_form(e: &Expr, src: &str) -> Option<String> {
    if let Expr::Function(f) = e {
        let name = f
            .name
            .0
            .last()
            .map(|i| i.value.to_ascii_uppercase())
            .unwrap_or_default();
        let arg_text = match &f.args {
            sqlparser::ast::FunctionArguments::List(l) => {
                let parts: Vec<String> = l
                    .args
                    .iter()
                    .map(|a| match a {
                        sqlparser::ast::FunctionArg::Unnamed(
                            sqlparser::ast::FunctionArgExpr::Expr(e),
                        ) => render_expr(e),
                        sqlparser::ast::FunctionArg::Unnamed(
                            sqlparser::ast::FunctionArgExpr::Wildcard,
                        ) => "*".to_string(),
                        other => format!("{other:?}"),
                    })
                    .collect();
                parts.join(", ")
            }
            _ => String::new(),
        };
        return Some(match (name.as_str(), arg_text.as_str()) {
            ("COUNT", "*") => format!("COUNT({src})"),
            ("COUNT", col) => format!("COUNT({src}.{})", strip_qualifier(col)),
            ("SUM", col) => format!("SUM({src}.{})", strip_qualifier(col)),
            ("AVG", col) => format!("AVG({src}.{})", strip_qualifier(col)),
            ("MIN", col) => format!("MIN({src}.{})", strip_qualifier(col)),
            ("MAX", col) => format!("MAX({src}.{})", strip_qualifier(col)),
            ("COLLECT_LIST", col) | ("COLLECT_SET", col) => {
                format!("{name}({src}.{})", strip_qualifier(col))
            }
            (other, args) => format!("{other}({args})"),
        });
    }
    None
}

// -------------------------------------------------------------------
// Expressions / values
// -------------------------------------------------------------------

fn render_expr(e: &Expr) -> String {
    // sqlparser's Display for Expr matches Pig Latin's expression
    // grammar closely enough (`a + b`, `a = 1`, `(x)`, `NOT e`) that we
    // just delegate, with a couple of patches for special cases.
    match e {
        Expr::Function(_) => e.to_string(),
        Expr::Value(Value::SingleQuotedString(s)) => format!("'{}'", s.replace('\'', "\\'")),
        _ => e.to_string(),
    }
}

fn render_order_keys(exprs: &[OrderByExpr]) -> String {
    exprs
        .iter()
        .map(|o| {
            let dir = match o.asc {
                Some(false) => " DESC",
                _ => " ASC",
            };
            format!("{}{dir}", render_expr(&o.expr))
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn discriminant<T: std::fmt::Debug>(t: &T) -> String {
    let s = format!("{t:?}");
    s.split('(').next().unwrap_or(&s).trim().to_string()
}
